# Generated by Django 4.2.1 on 2023-07-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_remove_student_email_remove_student_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='intake',
            field=models.CharField(default='Spring Intake', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default='Level 4', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='BSC Hons', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='StudentId',
        ),
    ]
