# Generated by Django 4.2.1 on 2023-07-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_alter_level_level_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='posted_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=None),
        ),
    ]
