# Generated by Django 4.2.1 on 2023-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0005_submittedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='submitted_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='submittedassignment',
            name='submitted_assignment',
            field=models.FileField(upload_to='assignments'),
        ),
    ]
