# Generated by Django 4.2.1 on 2023-08-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_assignment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalmark',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.course'),
        ),
        migrations.AddField(
            model_name='totalmark',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.level'),
        ),
    ]
