# Generated by Django 4.2.1 on 2023-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0011_alter_totalmark_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='posted_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
