# Generated by Django 4.2.1 on 2023-07-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0015_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(auto_now=True),
        ),
    ]
