# Generated by Django 4.2.1 on 2023-07-09 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0016_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
