# Generated by Django 4.2.1 on 2023-07-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0019_alter_attendance_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
