# Generated by Django 4.2.1 on 2023-07-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0022_examination_alter_subjectmarks_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark', models.IntegerField()),
                ('rank', models.IntegerField(null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Staff.student')),
            ],
        ),
    ]
