# Generated by Django 4.2.1 on 2023-08-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumystudent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
